base_url = "https://waitingfor.io"
title = "Waiting for I/O"

theme = "zola-theme-terminimal"

generate_feed = true
feed_filename = "atom.xml"

compile_sass = true
build_search_index = false

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
author = "Chip Turner"
page_titles = "combined"

menu_items = [
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
]